import Head from "next/head";

export default function People() {
  return (
    <div>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ textAlign: "center", width: "40%", margin: "auto" }}>
        <h1>Could not find the person</h1>
      </main>
    </div>
  );
}
